CREATE TABLE Cat (
    ID VARCHAR(5) PRIMARY KEY,
    Name VARCHAR(255),
    Birthday DATE,
    Gender VARCHAR(10),
    DateArrived DATE,
    Adopted VARCHAR(3) DEFAULT 'No'
);

CREATE TABLE Age (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Birthday DATE,
    Age INT,
    CatID VARCHAR(5),
    FOREIGN KEY (CatID) REFERENCES Cat(ID)
);

CREATE TABLE Age_Range (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Age INT,
    Age_Range VARCHAR(10),
    AgeID INT,
    FOREIGN KEY (AgeID) REFERENCES Age(ID)
);

CREATE TABLE Applicant (
    ID VARCHAR(5) PRIMARY KEY,
    Name VARCHAR(255),
    Email VARCHAR(255)
);

CREATE TABLE Adopter (
    ID VARCHAR(5) PRIMARY KEY,
    ApplicantID VARCHAR(5),
    CatID VARCHAR(5),
    FOREIGN KEY (ApplicantID) REFERENCES Applicant(ID),
    FOREIGN KEY (CatID) REFERENCES Cat(ID)
);